services:
  mysql:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flashcard-database
      - "TZ=America/Sao_Paulo"
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 20s
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/flashcard-database?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - "TZ=America/Sao_Paulo"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/home/app
      - ~/.m2:/root/.m2
networks:
  springapimysql-net:
