spring:
  application:
    name: flashcards-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/flashcard-database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
  flyway:
    baseline-on-migrate: true
    user: root
    password: root
    url: jdbc:mysql://mysql:3306/flashcard-database
    locations: classpath:db/migration
    baseline-version: 0
    validate-on-migrate: true
  sql:
    init:
      mode: always
